[package]
name = "big-number-math"
version = "0.1.0"
edition = "2021"
[lib]
name = "big_number_math"
path = "src/lib.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
